import {
  BedDouble,
  Facebook,
  Home,
  Instagram,
  Twitter,
  User,
  UtensilsCrossed,
  Youtube,
} from 'lucide-react';
import {
  HOME_IMAGES,
  ROOM_LISTING_IMAGES,
  OFFER_IMAGES,
  ABOUT_IMAGES,
} from './images';
import type {
  Testimonial,
  RoomListing,
  Offer,
  TeamMember,
  BookingRoom,
  GuestBooking,
  GuestNotification,
  GuestReview,
} from '@/type/type';
import { PromoData, RoomData } from '@/type/interface';

export const FEATURED_ROOMS = [
  {
    id: '1',
    image: HOME_IMAGES.rooms.deluxeKing,
    name: 'Deluxe Oasis King',
    description:
      'King Bed · City Views. A restful and rejuvenating atmosphere with premium furnishings and panoramic windows.',
    priceFrom: 350000,
    badge: null,
  },
  {
    id: '2',
    image: HOME_IMAGES.rooms.executiveView,
    name: 'Executive Grand Suite',
    description:
      'Spacious living area, floor-to-ceiling windows, and exclusive lounge access for the modern professional.',
    priceFrom: 750000,
    badge: null,
  },
  {
    id: '3',
    image: HOME_IMAGES.rooms.presidentialSuite,
    name: 'Presidential Penthouse',
    description:
      'The pinnacle of luxury — private terrace, butler service, and bespoke experiences crafted exclusively for you.',
    priceFrom: 1350000,
    badge: 'All Inclusive',
  },
] as const;

export const QUICK_LINKS = [
  { href: '/rooms', label: 'Our Suites' },
  { href: '/#dining', label: 'Dining Venues' },
  { href: '/#amenities', label: 'Spa & Wellness' },
  { href: '/#events', label: 'Meetings & Events' },
  { href: '/gallery', label: 'Photo Gallery' },
];



export const POLICY_LINKS = [
  { href: '/privacy', label: 'Privacy Policy' },
  { href: '/terms', label: 'Terms of Service' },
  { href: '/refunds', label: 'Refund Policy' },
  { href: '/accessibility', label: 'Accessibility' },
];

export const SOCIAL_LINKS = [
  { icon: Twitter, href: '#', label: 'Twitter — Grand Oasis Abuja' },
  { icon: Youtube, href: '#', label: 'YouTube — Grand Oasis Abuja' },
  { icon: Instagram, href: '#', label: 'Instagram — Grand Oasis Abuja' },
  { icon: Facebook, href: '#', label: 'Facebook — Grand Oasis Abuja' },
];

export const NAV_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/rooms', label: 'Rooms' },
  { href: '/offers', label: 'Offers' },
  { href: '/about', label: 'About Us' },
  { href: '/contact', label: 'Contact' },
];

export const ROOM_LISTINGS: RoomListing[] = [
  {
    id: 'executive-suite',
    image: ROOM_LISTING_IMAGES.executiveSuite,
    name: 'Executive Suite',
    price: 680000,
    rating: 4.9,
    reviewCount: 128,
    badge: 'recommended',
    beds: '2 King',
    guests: 4,
    sqft: 850,
    amenities: ['Pool', 'WiFi'],
  },
  {
    id: 'deluxe-terrace',
    image: ROOM_LISTING_IMAGES.deluxeTerrace,
    name: 'Deluxe Terrace',
    price: 480000,
    rating: 4.7,
    reviewCount: 95,
    badge: 'popular',
    beds: '1 King',
    guests: 2,
    sqft: 580,
    amenities: ['Pool View'],
  },
  {
    id: 'presidential-suite',
    image: ROOM_LISTING_IMAGES.presidentialSuite,
    name: 'Presidential Suite',
    price: 1875000,
    rating: 5.0,
    reviewCount: 42,
    badge: 'recommended',
    beds: '2 King',
    guests: 6,
    sqft: 1400,
    amenities: ['Private Bar'],
  },
  {
    id: 'panoramic-king',
    image: ROOM_LISTING_IMAGES.panoramicKing,
    name: 'Panoramic King',
    price: 570000,
    rating: 4.8,
    reviewCount: 76,
    badge: null,
    beds: '1 King',
    guests: 2,
    sqft: 620,
    amenities: ['City View', 'Spa Tub'],
  },
  {
    id: 'deluxe-king-garden',
    image: ROOM_LISTING_IMAGES.deluxeKingGarden,
    name: 'Deluxe King Garden View',
    price: 315000,
    rating: 4.6,
    reviewCount: 112,
    badge: null,
    beds: '1 King',
    guests: 2,
    sqft: 450,
    amenities: ['Garden View'],
  },
  {
    id: 'oceanfront-executive',
    image: ROOM_LISTING_IMAGES.oceanfrontExecutive,
    name: 'Oceanfront Executive Suite',
    price: 580000,
    rating: 4.8,
    reviewCount: 64,
    badge: 'popular',
    beds: '1 King',
    guests: 3,
    sqft: 720,
    amenities: ['Ocean View'],
  },
  {
    id: 'superior-studio',
    image: ROOM_LISTING_IMAGES.superiorStudio,
    name: 'Superior Single Studio',
    price: 220000,
    rating: 4.5,
    reviewCount: 203,
    badge: null,
    beds: '1 Queen',
    guests: 2,
    sqft: 380,
    amenities: ['WiFi'],
  },
  {
    id: 'grand-deluxe',
    image: ROOM_LISTING_IMAGES.grandDeluxe,
    name: 'Grand Deluxe Suite',
    price: 780000,
    rating: 4.9,
    reviewCount: 58,
    badge: null,
    beds: '2 King',
    guests: 4,
    sqft: 950,
    amenities: ['Pool', 'Spa'],
  },
];

export const ROOM_TYPES = [
  'Executive Suites',
  'Deluxe Rooms',
  'Standard King',
] as const;

export const ROOM_AMENITY_FILTERS = [
  'WiFi',
  'Pool Access',
  'Fitness Gym',
] as const;

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Williams',
    role: 'Business Traveler',
    rating: 5,
    review:
      'The attention to detail is remarkable. From the moment I stepped into the lobby, I felt like royalty. The spa treatments are simply the best in Abuja.',
    avatarColor: 'bg-[#7CA5B8]',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Holiday Guest',
    rating: 5,
    review:
      'An incredible stay. The rooftop restaurant offers breathtaking views of the city. Highly recommend the Executive Suite for anyone seeking luxury.',
    avatarColor: 'bg-[#9CA3AF]',
  },
  {
    id: '3',
    name: 'David Okoro',
    role: 'Event Organizer',
    rating: 5,
    review:
      'Perfect for our corporate retreat. The conference facilities are modern and the team was incredibly helpful throughout our event.',
    avatarColor: 'bg-[#A9DBBB]',
  },
];

export const OFFERS: Offer[] = [
  {
    id: 'romantic-getaway',
    image: OFFER_IMAGES.romanticGetaway,
    title: 'Romantic Getaway Package',
    description:
      'Escape into luxury with our signature romantic experience. Includes a stay in our Royal Suite, a three-course dinner under the stars at The Palm court, a bottle of vintage champagne, and a private 90-minute couples massage.',
    category: ['all', 'romantic'],
    discountText: 'SAVE 25% TODAY',
    originalPrice: 675000,
    price: 505000,
    priceLabel: '/night',
    terms: [
      'Min. 2 nights stay',
      '48h cancellation',
      'Subject to availability',
    ],
    isFeatured: true,
  },
  {
    id: 'business-traveler-special',
    image: OFFER_IMAGES.businessTraveler,
    title: 'Business Traveler Special',
    description:
      'Seamless stays for the modern professional. Includes high-speed Wi-Fi, executive lounge access, complimentary laundry for 2 items, and late check-out at 4:00 PM.',
    category: ['all', 'business'],
    badge: 'business',
    discountText: '15% OFF',
    price: 0,
    priceLabel: '',
    terms: [],
    disclaimer:
      'Valid for Sunday-Thursday stays only. Requires valid corporate ID.',
  },
  {
    id: 'weekend-spa-retreat',
    image: OFFER_IMAGES.spaRetreat,
    title: 'Weekend Spa Retreat',
    description:
      'Rejuvenate your spirit with our wellness weekend. Includes Deluxe Room, organic breakfast buffet, and unlimited access to thermal pools and sauna facilities.',
    category: ['all', 'seasonal'],
    badge: 'leisure',
    price: 315000,
    priceLabel: 'Fixed',
    terms: [],
    disclaimer:
      'Saturday night stay required. Spa treatments must be booked 24h in advance.',
  },
  {
    id: 'summer-escape',
    image: OFFER_IMAGES.summerEscape,
    title: 'Summer Escape',
    description:
      'Make the most of the season with poolside luxury. Includes daily breakfast, two complimentary cocktails, and late checkout.',
    category: ['all', 'seasonal', 'lastMinute'],
    price: 285000,
    priceLabel: '/night',
    terms: ['Valid June - August', 'Min. 3 nights'],
  },
  {
    id: 'family-fun-package',
    image: OFFER_IMAGES.familyFun,
    title: 'Family Fun Package',
    description:
      'Create lasting memories with your loved ones. Includes connecting rooms, kids eat free, access to our game room, and complimentary airport transfer.',
    category: ['all', 'seasonal'],
    price: 640000,
    priceLabel: '/night',
    terms: ['Valid for families with 2+ children', 'Weekend stays'],
  },
  {
    id: 'midweek-special',
    image: OFFER_IMAGES.midweekSpecial,
    title: 'Midweek Special',
    description:
      'Enjoy midweek tranquility at a special rate. Perfect for a quick getaway with complimentary room upgrade based on availability.',
    category: ['all', 'lastMinute'],
    discountText: '20% OFF',
    price: 240000,
    priceLabel: '/night',
    terms: ['Mon-Wed stays only', 'Book 48h in advance'],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Amara Okafor',
    role: 'General Manager',
    image: ABOUT_IMAGES.team.member1,
    bgColor: 'bg-[#5F9EA0]',
  },
  {
    id: '2',
    name: 'Fatima Bello',
    role: 'Head of Concierge',
    image: ABOUT_IMAGES.team.member2,
    bgColor: 'bg-[#8B7355]',
  },
  {
    id: '3',
    name: 'David Mensah',
    role: 'Executive Chef',
    image: ABOUT_IMAGES.team.member3,
    bgColor: 'bg-[#B8A99A]',
  },
  {
    id: '4',
    name: 'Zainab Yusuf',
    role: 'Operations Director',
    image: ABOUT_IMAGES.team.member4,
    bgColor: 'bg-[#4A5568]',
  },
];

export const GUEST_BOOKINGS: GuestBooking[] = [
  {
    id: 'BK-8821',
    roomType: 'Deluxe Suite',
    roomSubtype: 'King Size, Pool View',
    image: ROOM_LISTING_IMAGES.executiveSuite,
    checkIn: '2023-10-12',
    checkOut: '2023-10-15',
    nights: 3,
    amount: 255000,
    status: 'confirmed',
  },
  {
    id: 'BK-7901',
    roomType: 'Executive Room',
    roomSubtype: 'City View, Lounge Access',
    image: ROOM_LISTING_IMAGES.panoramicKing,
    checkIn: '2023-09-28',
    checkOut: '2023-09-30',
    nights: 2,
    amount: 192000,
    status: 'checked-in',
  },
  {
    id: 'BK-7742',
    roomType: 'Presidential Suite',
    roomSubtype: 'Top Floor, Private Terrace',
    image: ROOM_LISTING_IMAGES.presidentialSuite,
    checkIn: '2023-08-05',
    checkOut: '2023-08-10',
    nights: 5,
    amount: 1188000,
    status: 'checked-out',
  },
  {
    id: 'BK-6610',
    roomType: 'Standard Single',
    roomSubtype: 'Business Wing',
    image: ROOM_LISTING_IMAGES.superiorStudio,
    checkIn: '2023-06-20',
    checkOut: '2023-06-22',
    nights: 2,
    amount: 126000,
    status: 'cancelled',
  },
  {
    id: 'BK-6421',
    roomType: 'Grand Deluxe Suite',
    roomSubtype: 'Rooftop Pool Access',
    image: ROOM_LISTING_IMAGES.grandDeluxe,
    checkIn: '2023-05-14',
    checkOut: '2023-05-17',
    nights: 3,
    amount: 450000,
    status: 'confirmed',
  },
  {
    id: 'BK-6105',
    roomType: 'Ocean View Suite',
    roomSubtype: 'Sea Front, Balcony',
    image: ROOM_LISTING_IMAGES.oceanfrontExecutive,
    checkIn: '2023-04-02',
    checkOut: '2023-04-06',
    nights: 4,
    amount: 576000,
    status: 'checked-out',
  },
  {
    id: 'BK-5890',
    roomType: 'Deluxe Terrace Room',
    roomSubtype: 'Garden View, Terrace',
    image: ROOM_LISTING_IMAGES.deluxeTerrace,
    checkIn: '2023-03-18',
    checkOut: '2023-03-20',
    nights: 2,
    amount: 150000,
    status: 'pending',
  },
  {
    id: 'BK-5677',
    roomType: 'Panoramic King Room',
    roomSubtype: 'Top Floor, City View',
    image: ROOM_LISTING_IMAGES.panoramicKing,
    checkIn: '2023-02-22',
    checkOut: '2023-02-25',
    nights: 3,
    amount: 333000,
    status: 'cancelled',
  },
  {
    id: 'BK-5301',
    roomType: 'Executive Suite',
    roomSubtype: 'City View, Lounge Access',
    image: ROOM_LISTING_IMAGES.executiveSuite,
    checkIn: '2023-01-10',
    checkOut: '2023-01-13',
    nights: 3,
    amount: 360000,
    status: 'checked-out',
  },
  {
    id: 'BK-5012',
    roomType: 'Superior Studio',
    roomSubtype: 'Garden Level',
    image: ROOM_LISTING_IMAGES.superiorStudio,
    checkIn: '2022-12-24',
    checkOut: '2022-12-26',
    nights: 2,
    amount: 98000,
    status: 'checked-out',
  },
];

export const BOOKING_HISTORY: GuestBooking[] = [
  {
    id: 'BK-8821',
    roomType: 'Deluxe King Room',
    roomSubtype: 'Pool View',
    image: ROOM_LISTING_IMAGES.executiveSuite,
    checkIn: '2023-10-12',
    checkOut: '2023-10-15',
    nights: 3,
    amount: 270000,
    status: 'checked-out',
  },
  {
    id: 'BK-7654',
    roomType: 'Ocean View Suite',
    roomSubtype: 'Sea View',
    image: ROOM_LISTING_IMAGES.oceanfrontExecutive,
    checkIn: '2023-08-20',
    checkOut: '2023-08-25',
    nights: 5,
    amount: 720000,
    status: 'checked-out',
  },
  {
    id: 'BK-6543',
    roomType: 'Standard Twin',
    roomSubtype: 'Garden View',
    image: ROOM_LISTING_IMAGES.deluxeKingGarden,
    checkIn: '2023-06-10',
    checkOut: '2023-06-12',
    nights: 2,
    amount: 126000,
    status: 'cancelled',
  },
  {
    id: 'BK-5432',
    roomType: 'Executive Suite',
    roomSubtype: 'City View',
    image: ROOM_LISTING_IMAGES.grandDeluxe,
    checkIn: '2023-05-01',
    checkOut: '2023-05-05',
    nights: 4,
    amount: 588000,
    status: 'checked-out',
  },
  {
    id: 'BK-5101',
    roomType: 'Presidential Suite',
    roomSubtype: 'Top Floor, Private Terrace',
    image: ROOM_LISTING_IMAGES.presidentialSuite,
    checkIn: '2023-03-15',
    checkOut: '2023-03-20',
    nights: 5,
    amount: 1485000,
    status: 'checked-out',
  },
  {
    id: 'BK-4890',
    roomType: 'Grand Deluxe Suite',
    roomSubtype: 'Rooftop Pool Access',
    image: ROOM_LISTING_IMAGES.grandDeluxe,
    checkIn: '2023-02-08',
    checkOut: '2023-02-11',
    nights: 3,
    amount: 450000,
    status: 'cancelled',
  },
  {
    id: 'BK-4612',
    roomType: 'Deluxe Terrace Room',
    roomSubtype: 'Garden View, Terrace',
    image: ROOM_LISTING_IMAGES.deluxeTerrace,
    checkIn: '2022-12-23',
    checkOut: '2022-12-27',
    nights: 4,
    amount: 300000,
    status: 'checked-out',
  },
  {
    id: 'BK-4301',
    roomType: 'Panoramic King Room',
    roomSubtype: 'Top Floor, City View',
    image: ROOM_LISTING_IMAGES.panoramicKing,
    checkIn: '2022-11-10',
    checkOut: '2022-11-12',
    nights: 2,
    amount: 222000,
    status: 'checked-out',
  },
  {
    id: 'BK-4010',
    roomType: 'Superior Studio',
    roomSubtype: 'Garden Level',
    image: ROOM_LISTING_IMAGES.superiorStudio,
    checkIn: '2022-10-05',
    checkOut: '2022-10-07',
    nights: 2,
    amount: 98000,
    status: 'cancelled',
  },
  {
    id: 'BK-3750',
    roomType: 'Deluxe King Suite',
    roomSubtype: 'King Size, Garden View',
    image: ROOM_LISTING_IMAGES.deluxeKingGarden,
    checkIn: '2022-09-01',
    checkOut: '2022-09-04',
    nights: 3,
    amount: 243000,
    status: 'checked-out',
  },
];

// BOOKING_ROOMS is no longer used in the booking wizard — rooms are fetched
// live from the API. This data is kept only as a reference and can be removed.
export const BOOKING_ROOMS: BookingRoom[] = [
  {
    id: 'deluxe-city-view',
    imageUrl: ROOM_LISTING_IMAGES.executiveSuite,
    name: 'Deluxe City View Suite',
    type: 'Deluxe',
    description:
      "Spacious 45sqm suite featuring breathtaking views of Abuja's skyline, premium bedding, and a marble-finished bathroom.",
    price: 8500000,
    beds: 'King',
    sqm: 45,
    maxGuests: 2,
    amenities: ['Free WiFi', 'Coffee Maker', 'Air Conditioning'],
  },
  {
    id: 'executive-king',
    imageUrl: ROOM_LISTING_IMAGES.panoramicKing,
    name: 'Executive King Room',
    type: 'Executive',
    description:
      'Exclusive access to the Executive Lounge, including complimentary breakfast and evening cocktails. Ideal for business travelers.',
    price: 12000000,
    beds: 'King',
    sqm: 60,
    maxGuests: 2,
    amenities: ['King Bed', 'Lounge Access', '55" Smart TV', 'Ergonomic Desk'],
  },
  {
    id: 'presidential-suite',
    imageUrl: ROOM_LISTING_IMAGES.presidentialSuite,
    name: 'Presidential Suite',
    type: 'Suite',
    description:
      'The pinnacle of luxury with a private terrace, butler service, and bespoke experiences crafted exclusively for you.',
    price: 25000000,
    beds: 'King',
    sqm: 120,
    maxGuests: 4,
    amenities: ['Private Terrace', 'Butler Service', 'Private Bar', 'Jacuzzi'],
  },
  {
    id: 'deluxe-terrace',
    imageUrl: ROOM_LISTING_IMAGES.deluxeTerrace,
    name: 'Deluxe Terrace Room',
    type: 'Deluxe',
    description:
      'A serene retreat with a private terrace overlooking lush gardens. Perfect for a peaceful getaway.',
    price: 7500000,
    beds: 'Queen',
    sqm: 50,
    maxGuests: 2,
    amenities: ['Private Terrace', 'Garden View', 'Free WiFi', 'Minibar'],
  },
  {
    id: 'grand-deluxe',
    imageUrl: ROOM_LISTING_IMAGES.grandDeluxe,
    name: 'Grand Deluxe Suite',
    type: 'Suite',
    description:
      'Indulge in spacious comfort with premium furnishings, a dedicated living area, and access to our rooftop pool.',
    price: 15000000,
    beds: 'King',
    sqm: 80,
    maxGuests: 3,
    amenities: ['Pool Access', 'Living Area', 'King Bed', 'Spa Bath'],
  },
];

export const GUEST_NOTIFICATIONS: GuestNotification[] = [
  {
    id: 'notif-1',
    type: 'booking_confirmed',
    title: 'Booking Confirmed',
    message:
      'Your stay at Ocean View Resort has been successfully confirmed for Dec 15–20.',
    boldWord: 'Ocean View Resort',
    time: '2 mins ago',
    read: false,
    archived: false,
    actionLabel: 'View Details',
    actionHref: '/dashboard/guest',
  },
  {
    id: 'notif-2',
    type: 'checkout_reminder',
    title: 'Check-out Reminder',
    message:
      "Don't forget! Your check-out at Mountain Cabin Retreat is tomorrow by 11:00 AM.",
    boldWord: 'Mountain Cabin Retreat',
    time: '3 hours ago',
    read: false,
    archived: false,
    actionLabel: 'See Instructions',
    actionHref: '/dashboard/guest',
  },
  {
    id: 'notif-3',
    type: 'payment_received',
    title: 'Payment Received',
    message:
      "We've received your payment of ₦450,000 for your upcoming stay at The Grand Oasis.",
    boldWord: 'The Grand Oasis',
    time: 'Yesterday',
    read: true,
    archived: false,
    actionLabel: 'Download Receipt',
    actionHref: '/dashboard/guest',
  },
  {
    id: 'notif-4',
    type: 'review_prompt',
    title: 'How was your stay?',
    message:
      'Share your experience at Urban Loft. Your feedback helps other travelers!',
    boldWord: 'Urban Loft',
    time: '2 days ago',
    read: true,
    archived: false,
    actionLabel: 'Leave a Review',
    actionHref: '/dashboard/guest/reviews',
  },
  {
    id: 'notif-5',
    type: 'security',
    title: 'Profile Security Update',
    message:
      "A new login was detected from a Chrome browser on a Mac device. If this wasn't you, please change your password.",
    time: '5 days ago',
    read: true,
    archived: false,
    actionLabel: 'Review Activity',
    actionHref: '/dashboard/guest/profile',
  },
  {
    id: 'notif-6',
    type: 'booking_confirmed',
    title: 'Booking Confirmed',
    message:
      'Your reservation for the Executive Grand Suite (Nov 10–13) has been confirmed.',
    boldWord: 'Executive Grand Suite',
    time: '1 week ago',
    read: true,
    archived: true,
    actionLabel: 'View Details',
    actionHref: '/dashboard/guest',
  },
];

export const GUEST_REVIEWS: GuestReview[] = [
  {
    id: 'rev-1',
    bookingId: 'BK-8821',
    roomType: 'Deluxe King Suite',
    roomSubtype: 'King Size, Pool View',
    image:
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&q=80',
    checkIn: '2023-10-12',
    checkOut: '2023-10-15',
    rating: 5,
    reviewText:
      'Absolutely stunning stay. The pool view was breathtaking and the staff were incredibly attentive. Would book again without hesitation.',
    submittedAt: '2023-10-17',
  },
  {
    id: 'rev-2',
    bookingId: 'BK-7654',
    roomType: 'Ocean View Suite',
    roomSubtype: 'Ocean Front, Balcony',
    image:
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80',
    checkIn: '2023-08-20',
    checkOut: '2023-08-25',
    rating: 4,
    reviewText:
      'Beautiful room with stunning ocean views. Breakfast could be improved but overall a wonderful experience.',
    submittedAt: '2023-08-27',
  },
  {
    id: 'rev-3',
    bookingId: 'BK-7742',
    roomType: 'Presidential Suite',
    roomSubtype: 'Top Floor, Private Terrace',
    image:
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=400&q=80',
    checkIn: '2023-08-05',
    checkOut: '2023-08-10',
    rating: null,
    reviewText: null,
    submittedAt: null,
  },
  {
    id: 'rev-4',
    bookingId: 'BK-5432',
    roomType: 'Executive Suite',
    roomSubtype: 'City View, Lounge Access',
    image:
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=400&q=80',
    checkIn: '2023-05-01',
    checkOut: '2023-05-05',
    rating: null,
    reviewText: null,
    submittedAt: null,
  },
];


export const INITIAL_ROOMS: RoomData[] = [
  { id: 'RN-302-DX', roomNumber: 302, name: 'Deluxe King 302', type: 'Deluxe', price: 175000, status: 'Available', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-501-PS', roomNumber: 501, name: 'Presidential Suite 501', type: 'Suite', price: 600000, status: 'Occupied', image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-215-ST', roomNumber: 215, name: 'Standard Double 215', type: 'Standard', price: 90000, status: 'Maintenance', image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-410-EX', roomNumber: 410, name: 'Executive View 410', type: 'Executive', price: 275000, status: 'Available', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-601-GS', roomNumber: 601, name: 'Grand Suite 601', type: 'Suite', price: 850000, status: 'Available', image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-118-DT', roomNumber: 118, name: 'Deluxe Twin 118', type: 'Deluxe', price: 155000, status: 'Occupied', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-210-SS', roomNumber: 210, name: 'Standard Single 210', type: 'Standard', price: 75000, status: 'Available', image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-315-EC', roomNumber: 315, name: 'Executive Corner 315', type: 'Executive', price: 320000, status: 'Maintenance', image: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e3?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-420-PN', roomNumber: 420, name: 'Penthouse North 420', type: 'Suite', price: 1200000, status: 'Available', image: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=128&h=128&fit=crop&auto=format' },
  { id: 'RN-108-SQ', roomNumber: 108, name: 'Standard Queen 108', type: 'Standard', price: 82000, status: 'Occupied', image: 'https://images.unsplash.com/photo-1565791380713-1756b9a05343?w=128&h=128&fit=crop&auto=format' },
];


export const INITIAL_PROMOS: PromoData[] = [
  {
    code: 'GRAND25',
    description: '25% off all suites',
    discount: '25%',
    discountType: 'percentage',
    discountValue: 25,
    usageLimit: 100,
    used: 67,
    validFrom: 'Mar 1, 2026',
    validTo: 'Mar 31, 2026',
    status: 'Active',
  },
  {
    code: 'WELCOME15',
    description: '15% off first booking',
    discount: '15%',
    discountType: 'percentage',
    discountValue: 15,
    usageLimit: 500,
    used: 312,
    validFrom: 'Jan 1, 2026',
    validTo: 'Dec 31, 2026',
    status: 'Active',
  },
  {
    code: 'WEEKEND50K',
    description: '₦50,000 off weekend stays',
    discount: '₦50,000',
    discountType: 'fixed',
    discountValue: 50000,
    usageLimit: 50,
    used: 50,
    validFrom: 'Feb 1, 2026',
    validTo: 'Feb 28, 2026',
    status: 'Inactive',
  },
  {
    code: 'VIP2026',
    description: '30% off for VIP members',
    discount: '30%',
    discountType: 'percentage',
    discountValue: 30,
    usageLimit: 200,
    used: 88,
    validFrom: 'Jan 15, 2026',
    validTo: 'Jun 30, 2026',
    status: 'Active',
  },
  {
    code: 'EASTER100K',
    description: '₦100,000 off Easter holiday',
    discount: '₦100,000',
    discountType: 'fixed',
    discountValue: 100000,
    usageLimit: 75,
    used: 0,
    validFrom: 'Apr 17, 2026',
    validTo: 'Apr 20, 2026',
    status: 'Scheduled',
  },
  {
    code: 'NEWYR2025',
    description: 'New Year special offer',
    discount: '20%',
    discountType: 'percentage',
    discountValue: 20,
    usageLimit: 300,
    used: 300,
    validFrom: 'Dec 28, 2025',
    validTo: 'Jan 2, 2026',
    status: 'Inactive',
  },
];
